services:
    costs_bot:
        container_name: costs_bot
        build: ./
        image: costs_bot:latest
        restart: on-failure
        env_file:
            - .venv/.env
        secrets:
            - POSTGRES_PASSWORD
        ports:
            - "88:80"
        volumes:
            - bot:/bot/
        depends_on:
            - postgres

    postgres:
        container_name: postgres
        image: postgres:latest
        restart: on-failure
        environment:
            TZ: Etc/UTC
        env_file:
            - .venv/.env
        secrets:
            - POSTGRES_PASSWORD
        ports:
            - "5433:5432"
        volumes:
            - db_data:/var/lib/postgresql/data

volumes:
    bot:
    db_data:
        driver: local

secrets:
    TOKEN:
        file: .venv/.env
    POSTGRES_PASSWORD:
        file: .venv/.env
