CREATE TABLE COSTS (
    id SERIAL PRIMARY KEY,
    user_id INTEGER NOT NULL DEFAULT 0 REFERENCES users (id) ON DELETE CASCADE ON UPDATE CASCADE,
    message_id INTEGER NOT NULL DEFAULT 0 UNIQUE,
    amount DECIMAL(10, 2) NOT NULL DEFAULT 0 CHECK (amount >= 0),
    category VARCHAR(100) NOT NULL DEFAULT '',
    created TIMESTAMP
) PARTITION BY user_id
;

CREATE INDEX IDX_COSTS_USER_ID ON COSTS (user_id);
CREATE UNIQUE INDEX IDX_COSTS_ID_USER_ID ON COSTS (user_id, id);

COMMIT;
